import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Card, Container, Input, Spacer, Button } from '@nextui-org/react'
import bg from '../public/Wave-10s-3000px.svg'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div style={{
      backgroundImage: `url(${bg.src})`,
      margin: 0,
      width: '100%',
      height: '100vh',
      backgroundSize: 'auto',
      backgroundPosition: 'center center'
    }}>
      <Head>
        <title>Maximum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Card>
          <Card.Body>
            <Input placeholder="Read only" initialValue="readOnly" />
            <Spacer y={0.5} />
            <Input placeholder="Read only" initialValue="readOnly" />
            <Button>Entrar</Button>
          </Card.Body>
        </Card>
      </Container>
    </div>
  )
}
